import 'package:flutter/material.dart';

enum CommandExecutionMode {
  directAction,
  inputTemplate,
  installedAppPicker,
}

/// Representation of a supported offline Android command for DooraGo
class CommandItem {
  final String id;
  final String title;
  final String description;
  final IconData icon;
  final String example;
  final String category;
  final String requiredPermissions;
  final bool usesFunctionGemma;
  final bool requiresConfirmation;
  final CommandExecutionMode executionMode;
  final String? directCommand;
  final String? templateText;

  const CommandItem({
    required this.id,
    required this.title,
    required this.description,
    required this.icon,
    required this.example,
    required this.category,
    this.requiredPermissions = 'None',
    this.usesFunctionGemma = false,
    this.requiresConfirmation = false,
    this.executionMode = CommandExecutionMode.directAction,
    this.directCommand,
    this.templateText,
  });

  /// All supported categories in the DooraGo offline command center
  static const List<String> categories = [
    'All',
    'Device',
    'Connectivity',
    'Apps',
    'Phone',
    'Messages',
    'Email',
    'Maps',
    'Calendar',
    'Alarm & Timer',
    'Camera',
    'Files',
    'Information',
    'Sound',
    'Settings',
  ];

  /// Comprehensive structured command registry across all 14 offline categories
  static const List<CommandItem> allCommands = [
    // ── 1. Device ──
    CommandItem(
      id: 'turn_on_flashlight',
      title: 'Turn on Flashlight',
      description: 'Turns on the device torch / LED flashlight',
      icon: Icons.flashlight_on_rounded,
      example: 'Turn on flashlight / torch on karo',
      category: 'Device',
      requiredPermissions: 'CAMERA / FLASHLIGHT',
      usesFunctionGemma: true,
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Turn on flashlight',
    ),
    CommandItem(
      id: 'turn_off_flashlight',
      title: 'Turn off Flashlight',
      description: 'Turns off the device torch / LED flashlight',
      icon: Icons.flashlight_off_rounded,
      example: 'Turn off flashlight / torch band karo',
      category: 'Device',
      requiredPermissions: 'CAMERA / FLASHLIGHT',
      usesFunctionGemma: true,
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Turn off flashlight',
    ),
    CommandItem(
      id: 'open_device_settings',
      title: 'Device Settings',
      description: 'Opens main Android system settings',
      icon: Icons.settings_suggest_rounded,
      example: 'Open settings / settings kholo',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open settings',
    ),
    CommandItem(
      id: 'open_battery_settings',
      title: 'Battery Settings',
      description: 'Opens battery saver & usage settings',
      icon: Icons.battery_saver_rounded,
      example: 'Open battery settings / battery kholo',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open battery settings',
    ),
    CommandItem(
      id: 'open_display_settings',
      title: 'Display Settings',
      description: 'Opens screen brightness and display settings',
      icon: Icons.brightness_6_rounded,
      example: 'Open display settings / brightness settings',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open display settings',
    ),
    CommandItem(
      id: 'open_storage_settings',
      title: 'Storage Settings',
      description: 'Opens device storage management',
      icon: Icons.storage_rounded,
      example: 'Open storage settings / storage kholo',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open storage settings',
    ),
    CommandItem(
      id: 'open_app_settings',
      title: 'App Management',
      description: 'Opens installed applications settings',
      icon: Icons.apps_rounded,
      example: 'Open app settings / manage apps',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open app settings',
    ),
    CommandItem(
      id: 'open_accessibility_settings',
      title: 'Accessibility Settings',
      description: 'Opens accessibility controls and features',
      icon: Icons.accessibility_new_rounded,
      example: 'Open accessibility settings',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open accessibility settings',
    ),
    CommandItem(
      id: 'open_language_settings',
      title: 'Language Settings',
      description: 'Opens system language and input settings',
      icon: Icons.language_rounded,
      example: 'Open language settings / bhasha badlo',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open language settings',
    ),
    CommandItem(
      id: 'open_datetime_settings',
      title: 'Date & Time Settings',
      description: 'Opens system date and time settings',
      icon: Icons.schedule_rounded,
      example: 'Open date and time settings',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open date and time settings',
    ),
    CommandItem(
      id: 'open_developer_options',
      title: 'Developer Options',
      description: 'Opens developer options if unlocked',
      icon: Icons.developer_mode_rounded,
      example: 'Open developer options',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open developer options',
    ),
    CommandItem(
      id: 'open_about_phone',
      title: 'About Phone',
      description: 'Opens device status and specifications screen',
      icon: Icons.phone_android_rounded,
      example: 'Open about phone / about device',
      category: 'Device',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open about phone',
    ),

    // ── 2. Connectivity ──
    CommandItem(
      id: 'open_wifi_settings',
      title: 'Wi-Fi Settings',
      description: 'Opens system Wi-Fi settings',
      icon: Icons.wifi_rounded,
      example: 'Open WiFi settings / wifi kholo',
      category: 'Connectivity',
      usesFunctionGemma: true,
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open WiFi settings',
    ),
    CommandItem(
      id: 'open_bluetooth_settings',
      title: 'Bluetooth Settings',
      description: 'Opens Bluetooth paired devices & settings',
      icon: Icons.bluetooth_rounded,
      example: 'Open bluetooth settings / bluetooth kholo',
      category: 'Connectivity',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open Bluetooth settings',
    ),
    CommandItem(
      id: 'open_network_settings',
      title: 'Mobile Network Settings',
      description: 'Opens cellular network & SIM settings',
      icon: Icons.network_cell_rounded,
      example: 'Open mobile network settings',
      category: 'Connectivity',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open mobile network settings',
    ),
    CommandItem(
      id: 'open_internet_settings',
      title: 'Internet Settings',
      description: 'Opens system network & internet settings',
      icon: Icons.language_rounded,
      example: 'Open internet settings',
      category: 'Connectivity',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open internet settings',
    ),
    CommandItem(
      id: 'open_hotspot_settings',
      title: 'Hotspot & Tethering',
      description: 'Opens portable hotspot & tethering settings',
      icon: Icons.wifi_tethering_rounded,
      example: 'Open hotspot settings / hotspot kholo',
      category: 'Connectivity',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open hotspot settings',
    ),
    CommandItem(
      id: 'open_vpn_settings',
      title: 'VPN Settings',
      description: 'Opens system VPN configuration',
      icon: Icons.vpn_lock_rounded,
      example: 'Open VPN settings / vpn kholo',
      category: 'Connectivity',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open VPN settings',
    ),
    CommandItem(
      id: 'open_airplane_settings',
      title: 'Airplane Mode Settings',
      description: 'Opens airplane mode screen',
      icon: Icons.airplanemode_active_rounded,
      example: 'Open airplane mode settings / flight mode',
      category: 'Connectivity',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open airplane mode settings',
    ),

    // ── 3. Sound ──
    CommandItem(
      id: 'open_sound_settings',
      title: 'Sound & Volume Settings',
      description: 'Opens ringtone, media & notification volumes',
      icon: Icons.volume_up_rounded,
      example: 'Open sound settings / volume settings',
      category: 'Sound',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open sound settings',
    ),
    CommandItem(
      id: 'open_notification_settings',
      title: 'Notification Settings',
      description: 'Opens app notifications management',
      icon: Icons.notifications_active_rounded,
      example: 'Open notification settings',
      category: 'Sound',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open notification settings',
    ),
    CommandItem(
      id: 'open_dnd_settings',
      title: 'Do Not Disturb Settings',
      description: 'Opens Do Not Disturb priority settings',
      icon: Icons.do_not_disturb_on_rounded,
      example: 'Open DND settings / do not disturb kholo',
      category: 'Sound',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open DND settings',
    ),

    // ── 4. Apps ──
    CommandItem(
      id: 'open_youtube',
      title: 'Open YouTube',
      description: 'Launches the YouTube application',
      icon: Icons.play_circle_fill_rounded,
      example: 'Open YouTube / youtube kholo',
      category: 'Apps',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open YouTube',
    ),
    CommandItem(
      id: 'open_whatsapp',
      title: 'Open WhatsApp',
      description: 'Launches WhatsApp messenger',
      icon: Icons.chat_rounded,
      example: 'Open WhatsApp / whatsapp kholo',
      category: 'Apps',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open WhatsApp',
    ),
    CommandItem(
      id: 'open_chrome',
      title: 'Open Chrome',
      description: 'Launches Google Chrome browser',
      icon: Icons.public_rounded,
      example: 'Open Chrome / chrome kholo',
      category: 'Apps',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open Chrome',
    ),
    CommandItem(
      id: 'open_instagram',
      title: 'Open Instagram',
      description: 'Launches Instagram application',
      icon: Icons.camera_alt_rounded,
      example: 'Open Instagram / instagram kholo',
      category: 'Apps',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open Instagram',
    ),
    CommandItem(
      id: 'open_telegram',
      title: 'Open Telegram',
      description: 'Launches Telegram messenger',
      icon: Icons.send_rounded,
      example: 'Open Telegram / telegram kholo',
      category: 'Apps',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open Telegram',
    ),
    CommandItem(
      id: 'open_calculator',
      title: 'Open Calculator',
      description: 'Launches the device calculator',
      icon: Icons.calculate_rounded,
      example: 'Open calculator / calculator kholo',
      category: 'Apps',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open Calculator',
    ),
    CommandItem(
      id: 'open_clock',
      title: 'Open Clock',
      description: 'Launches device Clock & World Time',
      icon: Icons.access_time_rounded,
      example: 'Open Clock / clock kholo',
      category: 'Apps',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open Clock',
    ),
    CommandItem(
      id: 'open_installed_app',
      title: 'Open Any Installed App',
      description: 'Dynamically searches and opens any installed app',
      icon: Icons.apps_rounded,
      example: 'Open Instagram / Open Spotify / Open Uber',
      category: 'Apps',
      executionMode: CommandExecutionMode.installedAppPicker,
      directCommand: 'Open Any Installed App',
    ),

    // ── 5. Phone ──
    CommandItem(
      id: 'open_phone_dialer',
      title: 'Open Phone Dialer',
      description: 'Opens the phone keypad and call logs',
      icon: Icons.call_rounded,
      example: 'Open phone / phone dialer kholo',
      category: 'Phone',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open phone',
    ),
    CommandItem(
      id: 'dial_phone_number',
      title: 'Dial Number',
      description: 'Prepares a call in the dialer with given number',
      icon: Icons.dialpad_rounded,
      example: 'Dial a phone number / Call a number',
      category: 'Phone',
      requiresConfirmation: true,
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Call ',
    ),
    CommandItem(
      id: 'call_contact_name',
      title: 'Call Contact',
      description: 'Calls a saved contact by name using offline address book',
      icon: Icons.phone_forwarded_rounded,
      example: 'Call a contact / Contact ko call karo',
      category: 'Phone',
      requiredPermissions: 'READ_CONTACTS / CALL_PHONE',
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Call ',
    ),
    CommandItem(
      id: 'open_contacts_list',
      title: 'Open Contacts',
      description: 'Opens device contacts address book',
      icon: Icons.contacts_rounded,
      example: 'Open contacts / contacts kholo',
      category: 'Phone',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open contacts',
    ),
    CommandItem(
      id: 'create_contact',
      title: 'Create Contact',
      description: 'Opens contact creation with name, phone and email',
      icon: Icons.person_add_rounded,
      example: 'Save a contact / Contact save karo',
      category: 'Phone',
      usesFunctionGemma: true,
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Create a contact named ',
    ),

    // ── 6. Messages ──
    CommandItem(
      id: 'open_sms_composer',
      title: 'Send SMS / Text',
      description: 'Opens SMS composer with recipient and message',
      icon: Icons.sms_rounded,
      example: 'Send an SMS message / SMS bhejo',
      category: 'Messages',
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Send SMS to ',
    ),
    CommandItem(
      id: 'send_whatsapp_message',
      title: 'WhatsApp Message',
      description: 'Opens WhatsApp chat with recipient and message',
      icon: Icons.chat_rounded,
      example: 'Send a WhatsApp message / WhatsApp message bhejo',
      category: 'Messages',
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'WhatsApp ',
    ),

    // ── 7. Email ──
    CommandItem(
      id: 'send_email',
      title: 'Send Email',
      description: 'Opens email compose with recipient, subject & body',
      icon: Icons.email_rounded,
      example: 'Send an email / Email bhejo',
      category: 'Email',
      usesFunctionGemma: true,
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Send an email to ',
    ),

    // ── 8. Maps & Navigation ──
    CommandItem(
      id: 'show_map',
      title: 'Show Map Location',
      description: 'Searches and opens a location in the map app',
      icon: Icons.map_rounded,
      example: 'Show Jaipur on map / Taj Mahal dikhao',
      category: 'Maps',
      usesFunctionGemma: true,
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Show ',
    ),
    CommandItem(
      id: 'open_directions',
      title: 'Directions & Navigation',
      description: 'Opens turn-by-turn navigation to destination',
      icon: Icons.navigation_rounded,
      example: 'Navigate to Delhi / Delhi ka rasta dikhao',
      category: 'Maps',
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Navigate to ',
    ),

    // ── 9. Camera & Gallery ──
    CommandItem(
      id: 'open_camera_app',
      title: 'Open Camera',
      description: 'Opens the system camera to take photos',
      icon: Icons.photo_camera_rounded,
      example: 'Open camera / camera kholo',
      category: 'Camera',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open camera',
    ),
    CommandItem(
      id: 'open_gallery_app',
      title: 'Open Gallery / Photos',
      description: 'Opens device photo gallery',
      icon: Icons.photo_library_rounded,
      example: 'Open gallery / photos kholo',
      category: 'Camera',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open gallery',
    ),

    // ── 10. Calendar ──
    CommandItem(
      id: 'create_calendar_event',
      title: 'Create Calendar Event',
      description: 'Schedules an event with relative date/time',
      icon: Icons.event_rounded,
      example: 'Create a calendar event tomorrow at 5 PM',
      category: 'Calendar',
      usesFunctionGemma: true,
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Create a calendar event ',
    ),

    // ── 11. Alarm & Timer ──
    CommandItem(
      id: 'set_alarm',
      title: 'Set Alarm',
      description: 'Creates a device alarm for the requested time',
      icon: Icons.alarm_add_rounded,
      example: 'Set an alarm for 6:30 AM / 6 baje ka alarm lagao',
      category: 'Alarm & Timer',
      requiredPermissions: 'SET_ALARM',
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Set alarm for ',
    ),
    CommandItem(
      id: 'open_alarms',
      title: 'Open Alarms',
      description: 'Opens the clock and alarm list',
      icon: Icons.alarm_rounded,
      example: 'Open alarms / alarms kholo',
      category: 'Alarm & Timer',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open alarms',
    ),
    CommandItem(
      id: 'set_timer',
      title: 'Set Timer',
      description: 'Starts a countdown timer for specified duration',
      icon: Icons.timer_rounded,
      example: 'Set a timer for 10 minutes / 5 minute ka timer',
      category: 'Alarm & Timer',
      requiredPermissions: 'SET_ALARM',
      executionMode: CommandExecutionMode.inputTemplate,
      templateText: 'Set timer for ',
    ),

    // ── 12. Files ──
    CommandItem(
      id: 'open_files',
      title: 'Open Files',
      description: 'Opens system file browser / storage viewer',
      icon: Icons.folder_rounded,
      example: 'Open files / files kholo',
      category: 'Files',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open files',
    ),
    CommandItem(
      id: 'open_downloads',
      title: 'Open Downloads',
      description: 'Opens downloaded files and documents',
      icon: Icons.download_rounded,
      example: 'Open downloads / downloads kholo',
      category: 'Files',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open downloads',
    ),

    // ── 13. Information ──
    CommandItem(
      id: 'get_battery_status',
      title: 'Battery Percentage',
      description: 'Checks current battery level & charging status locally',
      icon: Icons.battery_charging_full_rounded,
      example: 'What is my battery percentage? / battery kitna hai?',
      category: 'Information',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'What is my battery level?',
    ),
    CommandItem(
      id: 'get_android_version',
      title: 'Android Version',
      description: 'Reports device Android release and API level',
      icon: Icons.android_rounded,
      example: 'What Android version is this?',
      category: 'Information',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'What is my Android version?',
    ),
    CommandItem(
      id: 'get_device_model',
      title: 'Device Model',
      description: 'Reports phone manufacturer and model name',
      icon: Icons.info_outline_rounded,
      example: 'What device is this? / kon sa phone hai?',
      category: 'Information',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'What device is this?',
    ),
    CommandItem(
      id: 'get_storage_info',
      title: 'Available Storage',
      description: 'Reports free and total storage space',
      icon: Icons.disc_full_rounded,
      example: 'How much storage is available?',
      category: 'Information',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'How much storage is available?',
    ),

    // ── 14. Settings ──
    CommandItem(
      id: 'open_security_settings',
      title: 'Security Settings',
      description: 'Opens device security & lock screen options',
      icon: Icons.security_rounded,
      example: 'Open security settings',
      category: 'Settings',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open security settings',
    ),
    CommandItem(
      id: 'open_privacy_settings',
      title: 'Privacy Settings',
      description: 'Opens permission manager & privacy dashboard',
      icon: Icons.privacy_tip_rounded,
      example: 'Open privacy settings',
      category: 'Settings',
      executionMode: CommandExecutionMode.directAction,
      directCommand: 'Open privacy settings',
    ),
  ];
}
