/// Categories of supported on-device actions for MobileActions-270M
enum ActionCategory {
  systemSetting,
  deviceControl,
  appLaunch,
  clockAndTimer,
  mediaControl,
  query,
  unsupported,
}

/// Action definition parsed or generated by the on-device AI model
class CommandAction {
  final String actionName;
  final ActionCategory category;
  final Map<String, dynamic> parameters;
  final double confidence;
  final bool requiresUserConfirmation;

  const CommandAction({
    required this.actionName,
    required this.category,
    this.parameters = const {},
    this.confidence = 1.0,
    this.requiresUserConfirmation = false,
  });

  @override
  String toString() =>
      'CommandAction(action: $actionName, category: $category, params: $parameters)';
}

/// Execution outcome returned by ActionExecutor
class ActionResult {
  final bool isSuccess;
  final String feedbackMessage;
  final Map<String, dynamic>? extraData;
  final DateTime executedAt;

  const ActionResult({
    required this.isSuccess,
    required this.feedbackMessage,
    this.extraData,
    required this.executedAt,
  });

  static ActionResult unexecutedDevPlaceholder(String actionName) {
    return ActionResult(
      isSuccess: false,
      feedbackMessage: 'AI engine is not connected yet. ($actionName unexecuted)',
      executedAt: DateTime.now(),
    );
  }
}
